
name: CI

on:
  push:
    branches: ["main", "feat/**"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  lint:
    name: Lint (ruff_black_mypy)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install ruff black
      - name: Ruff
        run: ruff check .
      - name: Black
        run: black --check .

  hassfest:
    name: hassfest (metadata validation)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: home-assistant/actions/hassfest@master

  hacs:
    name: HACS validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: HACS validation
        uses: hacs/[email protected]
        with:
          category: integration
          ignore: brands description topics

  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install "homeassistant==2025.8.2" pytest pytest-asyncio pytest-cov
      - name: Run tests
        run: pytest -q --maxfail=1 --disable-warnings
