
name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build zip
        run: |
          mkdir -p dist
          zip -r dist/powerwall_dashboard_energy_import.zip custom_components/powerwall_dashboard_energy_import README.md CHANGELOG.md pyproject.toml hacs.json || true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/powerwall_dashboard_energy_import.zip
          generate_release_notes: true
