
name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build zip
        run: |
          mkdir -p dist
          zip -r dist/powerwall_dashboard_energy_import.zip custom_components hacs.json LICENSE README.md CHANGELOG.md pyproject.toml requirements-test.txt || true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/powerwall_dashboard_energy_import.zip
